### ISSUE TITLE
The score of ndt-gpu

### ISSUE THREAD

**Issue by zorosmith** [EdwardLiuyc/calibration#3]
hello @EdwardLiuyc , I am reading your code, ndt_gicp.h.
`ndt_score = ndt_.getFitnessScore();
 #ifdef NDT_USE_GPU
 ndt_score /= 20;
 #endif`
I am wondering why the ndt_score should be divided by 20?
Look forward to your reply!
Thank you!

**Comment by EdwardLiuyc** [comment]
hello @zorosmith 
the macro `NDT_USE_GPU` is defined only when using **cuda version ndt**, you can refer to [Autoware](https://github.com/autowarefoundation/autoware) for more info of NDT_GPU
when using this version of ndt, I am also confused that the score is **not <=1**. so I make this normalization just to use it like a ndt regstrator in PCL.
Simply, It is **not recommended** to use the  GPU version.

**Comment by zorosmith** [comment]
ok！
Thank you for ur reply.
It helps！
